# SSI/DID Management System Benchmark Configuration for Caliper

# Common SSI benchmark arguments
ssiArgs: &ssi-args
  didPrefix: "did:besu:"
  issuerCount: 5
  holderCount: 10
  verifierCount: 2
  gasLimit: 6000000
  web3signerUrl: "http://127.0.0.1:18545"
  besuEndpoint: "http://172.16.239.15:8545"
  chainId: 1337
  contractAddresses:
    DIDRegistry: "0x1F2077A4Caa6a373A6bf628e30826Fd957C1b256"
    CredentialRegistry: "0xA5134e42CF382152894d040a0e89F2E4231062d8"

# Test configuration
test:
  name: SSI/DID Management System Performance Benchmark on Besu
  description: >
    Benchmark SSI operations on Hyperledger Besu with CLIQUE consensus.
    Tests various DID and Verifiable Credential operations.
  workers:
    number: 2
  rounds:
    - label: registerDID
      description: Register new DIDs in the SSI system
      txNumber: 10
      rateControl:
        type: fixed-rate
        opts:
          tps: 2 # Conservative TPS for CLIQUE's 15-second block time
      workload:
        module: benchmarks/registerDID.js
        arguments: *ssi-args

    # Additional rounds could be added for:
    # - updateDID
    # - resolveDID
    # - deactivateDID
    # - issueCredential
    # - verifyCredential

  # Monitoring configuration
  monitor:
    type:
      - prometheus
    prometheus:
      url: "http://localhost:9090"
      metrics:
        include:
          - besu_blockchain_difficulty_total
          - besu_blockchain_height
          - process_cpu_seconds_total
          - process_resident_memory_bytes
          - txpool_pending
          - txpool_queued
    interval: 5
